# Generated by Django 3.1.5 on 2021-02-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_auto_20210209_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(default='deef', max_length=30),
        ),
    ]
