# Generated by Django 3.1.5 on 2021-02-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', upload_to='interviews/thumbnail'),
        ),
    ]
