# Generated by Django 3.1.5 on 2021-02-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0009_interview_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='thumbnail',
            field=models.ImageField(default='interview/thumbnail/default.jpg', upload_to='interviews/thumbnail'),
        ),
    ]
