# Generated by Django 3.1.5 on 2021-02-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0010_auto_20210211_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='subtitles',
            field=models.FileField(blank=True, upload_to='interviews/subtitles'),
        ),
    ]
